### ISSUE TITLE
Error running map_new_seurat_hypoMap

### ISSUE THREAD

**Issue by CristinaRisu** [lsteuernagel/mapscvi#4]
Hi,

I'm trying to use the package to annotate my own dataset following the example, but I got the following error:
![image](https://github.com/lsteuernagel/mapscvi/assets/92274646/abb38078-2978-4fef-9e24-cb9891820df1)
maybe I'm not applying something right, could you help me to fix it? 
Thank you !

**Comment by lsteuernagel** [comment]
Dear Christina,

This is caused by a file check for the model.pt file at the very start of the function. This file comes with the package, so should be there. I slightly modfied that check to hopefully ensure that it is correctly found if it exists. Maybe you could re-install the package and check if the error still occurs ?

If it does, please make sure that the path shown in the error really contains the model.pt file. Maybe something went wrong during the installation. 

Best,

Lukas
